server:
  host: 0.0.0.0
  port: "8080"
auth:
  username: udin
  password_hash: $2a$10$jtQyCMiHL5EF15lPK/0SuuHvRn5AlHvJ4jntprFymfQqTNRCmM64i
servers_config_path: /Users/qindexmedia/.php-server-manager/config.json
acme:
  enabled: false
  email: ""
  domains: []
  storage_path: .php-server-manager/certs
